---
- name: Copy the cert to a holding spot

  hosts: le_cert_source

  become: yes
  become_method: sudo

  vars_files:
    - /home/ansible/lab/secrets/become-pw

  tasks:
    - include: cert_sync_subtasks.yml
      with_items:
        - "domain1.com"
        - "domain2.com"
      loop_control:
        loop_var: domain
