- name: Ensure the destination directory exists
  file:
    path: "/etc/pki/tls/{{ domain }}"
    state: directory
    owner: "{{ cert_user | default('root') }}"
    group: "{{ cert_group | default('root') }}"
    mode: 0550

- name: Copy the cert and key
  copy:
    src: "/etc/pki/tls/{{ domain }}/{{ item }}"
    dest: "/etc/pki/tls/{{ domain }}/{{ item }}"
    owner: "{{ cert_user }}"
    group: "{{ cert_group }}"
    mode: "{{ cert_mode }}"
  with_items:
    - fullchain.pem
    - privkey.pem
